# Generated by Django 4.2.30 on 2026-05-29 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='archives/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('disposed', 'Disposed'), ('rejected', 'Rejected'), ('final', 'Final')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.category')),
            ],
        ),
    ]
