# Generated by Django 4.2.30 on 2026-05-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('proposal', 'Proposal Permohonan'), ('sppd', 'SPPD (Perjalanan Dinas)'), ('dokumen_lainnya', 'Dokumen Lainnya')], default='surat_masuk', max_length=50),
        ),
        migrations.AddField(
            model_name='archive',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='sender_receiver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
