# Generated by Django 4.2.30 on 2026-05-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_archive_archive_type_archive_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
