# Generated by Django 4.2.30 on 2026-06-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_archive_result_file_archive_result_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('terverifikasi', 'Terverifikasi'), ('didisposisikan', 'Didisposisikan'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
