# Generated by Django 4.2.30 on 2026-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_alter_archive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('terverifikasi', 'Terverifikasi'), ('didisposisikan', 'Didisposisikan'), ('proses', 'Proses (SPPD)'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='baru', max_length=20),
        ),
    ]
