# Generated by Django 4.2.30 on 2026-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_archive_rejection_note_alter_archive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='drive_backed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
