# Generated by Django 4.2.30 on 2026-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_archive_drive_backed_up_archive_drive_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('proposal', 'Proposal Permohonan'), ('sppd', 'SPPD (Perjalanan Dinas)'), ('dokumen_lainnya', 'Dokumen Lainnya')], db_index=True, default='surat_masuk', max_length=50),
        ),
        migrations.AlterField(
            model_name='archive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
