# Generated by Django 4.2.30 on 2026-07-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_alter_archive_archive_type_alter_archive_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='sender_receiver',
        ),
        migrations.AddField(
            model_name='archive',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Diterima / Dikirim'),
        ),
        migrations.AddField(
            model_name='archive',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Penerima / Tujuan Surat'),
        ),
        migrations.AddField(
            model_name='archive',
            name='security_level',
            field=models.CharField(choices=[('biasa', 'Biasa'), ('penting', 'Penting'), ('rahasia', 'Rahasia'), ('sangat_rahasia', 'Sangat Rahasia')], default='biasa', max_length=20, verbose_name='Sifat Keamanan'),
        ),
        migrations.AddField(
            model_name='archive',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pengirim / Asal Instansi'),
        ),
        migrations.AddField(
            model_name='archive',
            name='urgency_level',
            field=models.CharField(choices=[('biasa', 'Biasa'), ('segera', 'Segera'), ('amat_segera', 'Amat Segera / Kilat')], default='biasa', max_length=20, verbose_name='Sifat Tanggapan'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomor Surat/Arsip'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('proposal', 'Proposal Permohonan (Zakat/Infak)'), ('sppd', 'Dokumen SPPD (Internal)'), ('dokumen_lainnya', 'Dokumen Lainnya')], db_index=True, default='surat_masuk', max_length=50, verbose_name='Jenis Dokumen'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Ringkas / Sinopsis'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_path',
            field=models.FileField(upload_to='archives/%Y/%m/%d/', verbose_name='File Dokumen Utama'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Surat'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='rejection_note',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan Arispan'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/', verbose_name='File Bukti Tindak Lanjut'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='result_note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Hasil / Laporan Staf'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru (Menunggu Verifikasi)'), ('terverifikasi', 'Terverifikasi (Siap Didisposisikan)'), ('didisposisikan', 'Dalam Proses Disposisi'), ('proses', 'Diproses Staf (Tindak Lanjut/SPPD)'), ('selesai', 'Selesai (Diarsipkan)'), ('ditolak', 'Ditolak/Dikembalikan')], db_index=True, default='baru', max_length=20),
        ),
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Perihal / Judul Dokumen'),
        ),
    ]
