# Generated by Django 4.2.30 on 2026-07-21 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0010_remove_archive_sender_receiver_archive_received_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='archive',
            name='kabid_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan / Checklist Verifikasi Kabid 4'),
        ),
        migrations.AddField(
            model_name='archive',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi Kabid 4'),
        ),
        migrations.AddField(
            model_name='archive',
            name='verified_by_kabid',
            field=models.BooleanField(default=False, verbose_name='Telah Diverifikasi Kabid 4'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('proposal', 'Proposal Permohonan (Zakat/Infak)'), ('undangan', 'Surat Undangan Eksternal'), ('sppd', 'Dokumen SPPD (Internal)'), ('dokumen_lainnya', 'Dokumen Lainnya')], db_index=True, default='surat_masuk', max_length=50, verbose_name='Jenis Dokumen'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='rejection_note',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan Arsip'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/', verbose_name='File Bukti Tindak Lanjut / Laporan Akhir'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru (Menunggu Verifikasi Sekretariat)'), ('verifikasi_kabid', 'Proses Verifikasi Kabid 4'), ('disposisi_pimpinan', 'Menunggu Disposisi Pimpinan'), ('terverifikasi', 'Terverifikasi (Siap Didisposisikan)'), ('didisposisikan', 'Dalam Proses Disposisi Pimpinan'), ('proses', 'Diproses Staf / Bidang'), ('menghadiri_undangan', 'Menghadiri Undangan / Acara Luar'), ('dalam_survei', 'Dalam Survei / Verifikasi Lapangan'), ('telah_disalurkan', 'Telah Disalurkan / Pentasyarufan'), ('selesai', 'Selesai & Terekap'), ('ditolak', 'Ditolak / Dikembalikan')], db_index=True, default='baru', max_length=30),
        ),
        migrations.AlterField(
            model_name='archive',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_archives', to=settings.AUTH_USER_MODEL),
        ),
    ]
