# Generated by Django 4.2.30 on 2026-07-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_alter_category_options_archive_kabid_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('proposal', 'Proposal Permohonan Bantuan'), ('laporan', 'Laporan UPZ'), ('dokumen_lainnya', 'Dokumen Lainnya')], db_index=True, default='surat_masuk', max_length=50, verbose_name='Jenis Dokumen'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru (Menunggu Verifikasi Sekretariat)'), ('verifikasi_kabid', 'Proses Verifikasi Kabid 4'), ('disposisi_pimpinan', 'Menunggu Disposisi Pimpinan'), ('terverifikasi', 'Terverifikasi (Siap Didisposisikan)'), ('didisposisikan', 'Dalam Proses Disposisi Pimpinan'), ('proses', 'Diproses Staf / Bidang'), ('sudah_ditugaskan', 'Penugasan (Surat Tugas Terbit)'), ('menghadiri_undangan', 'Menghadiri Undangan / Acara Luar'), ('dalam_survei', 'Dalam Survei / Verifikasi Lapangan'), ('telah_disalurkan', 'Telah Disalurkan / Pentasyarufan'), ('selesai', 'Selesai & Terekap'), ('ditolak', 'Ditolak / Dikembalikan')], db_index=True, default='baru', max_length=30),
        ),
    ]
