# Generated by Django 4.2.30 on 2026-07-29 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0012_alter_archive_archive_type_alter_archive_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_workflow', to='archives.archive')),
            ],
            options={
                'verbose_name': 'Alur Kerja Dokumen',
                'verbose_name_plural': 'Alur Kerja Dokumen',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Alur Kerja')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alur Kerja',
                'verbose_name_plural': 'Alur Kerja',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Langkah')),
                ('status_key', models.CharField(blank=True, help_text='Nilai status pada model Archive yang memicu langkah ini.', max_length=50, null=True, verbose_name='Status Arsip Terkait')),
                ('order', models.IntegerField(default=1, verbose_name='Urutan')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Dapat Dilewati')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_template', to='archives.workflow')),
            ],
            options={
                'verbose_name': 'Langkah Alur Kerja',
                'verbose_name_plural': 'Langkah Alur Kerja',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, verbose_name='Aktivitas / Tindakan')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Catatan / Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='archives.archive')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Alur Kerja',
                'verbose_name_plural': 'Riwayat Alur Kerja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Langkah')),
                ('status_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Arsip Terkait')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('current', 'Sedang Berjalan'), ('completed', 'Selesai'), ('skipped', 'Dilewati')], default='pending', max_length=20, verbose_name='Status Langkah')),
                ('order', models.IntegerField(default=1, verbose_name='Urutan')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Dapat Dilewati')),
                ('is_custom', models.BooleanField(default=False, help_text='True jika langkah ini ditambahkan manual oleh pengguna.', verbose_name='Langkah Kustom')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='archives.documentworkflow')),
            ],
            options={
                'verbose_name': 'Langkah Dokumen',
                'verbose_name_plural': 'Langkah Dokumen',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='documentworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_documents', to='archives.workflow'),
        ),
    ]
