# Generated by Django 4.2.30 on 2026-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0014_sequencecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Lengkap Pemohon / Mustahik / Instansi'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('proposal', 'Proposal'), ('surat_keluar', 'Surat Keluar'), ('dokumen_internal', 'Dokumen Internal')], db_index=True, default='surat_masuk', max_length=50, verbose_name='Jenis Dokumen'),
        ),
    ]
