# Generated by Django 4.2.30 on 2026-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0015_archive_address_alter_archive_archive_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentworkflow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentworkflowstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sequencecounter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['order'], 'verbose_name': 'Langkah Alur Kerja'},
        ),
        migrations.AlterField(
            model_name='documentworkflowstep',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentworkflowstep',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentworkflowstep',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentworkflowstep',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentworkflowstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('current', 'Sedang Berjalan'), ('completed', 'Selesai'), ('skipped', 'Dilewati')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentworkflowstep',
            name='status_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='status_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Arsip Terkait'),
        ),
    ]
