# Generated by Django 4.2.30 on 2026-08-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_alter_documentworkflow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Perihal / Judul Dokumen'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='verified_by_kabid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Telah Diverifikasi Kabid 4'),
        ),
    ]
