# Generated by Django 4.2.30 on 2026-06-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositions', '0003_remove_disposition_receiver_disposition_forwarded_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sppd_number', models.CharField(max_length=100, unique=True)),
                ('destination', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('transportation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_users', models.ManyToManyField(related_name='sppd_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sppds', to='dispositions.disposition')),
            ],
        ),
    ]
