# Generated by Django 4.2.30 on 2026-06-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
