# Generated by Django 4.2.30 on 2026-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role_delete_role'),
        ('sppd_service', '0002_sppd_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sppd',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='sppd',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='sppd_assignments', to='users.employee'),
        ),
    ]
