# Generated by Django 4.2.30 on 2026-06-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0007_change_forwarded_to_to_employee'),
        ('sppd_service', '0003_remove_sppd_assigned_users_sppd_assigned_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppd',
            name='disposition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sppd', to='dispositions.disposition'),
        ),
    ]
