# Generated by Django 4.2.30 on 2026-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role_delete_role'),
        ('sppd_service', '0004_change_disposition_to_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='sppd_followers', to='users.employee'),
        ),
    ]
