# Generated by Django 4.2.30 on 2026-07-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0008_disposition_parent_alter_disposition_note'),
        ('users', '0008_department_parent_employee_acting_in_department_and_more'),
        ('sppd_service', '0005_add_followers_to_sppd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='budget_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sumber Dana / Mata Anggaran'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='sppd_assignments', to='users.employee', verbose_name='Pegawai yang Diperintah'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='departure_date',
            field=models.DateField(verbose_name='Tanggal Keberangkatan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Kota / Tempat Tujuan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='disposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppd_list', to='dispositions.disposition'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='sppd_followers', to='users.employee', verbose_name='Pengikut (Jika Ada)'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Dibatalkan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='return_date',
            field=models.DateField(verbose_name='Tanggal Kepulangan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='sppd_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomor SPPD'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='transportation',
            field=models.CharField(max_length=100, verbose_name='Kendaraan / Alat Transportasi'),
        ),
    ]
