# Generated by Django 4.2.30 on 2026-07-21 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_options_alter_employee_options_and_more'),
        ('dispositions', '0009_disposition_checked_by_kabid_disposition_kabid_note_and_more'),
        ('sppd_service', '0006_sppd_budget_source_alter_sppd_assigned_employees_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sppd',
            options={'verbose_name': 'SPPD', 'verbose_name_plural': 'SPPD (Surat Perintah Perjalanan Dinas)'},
        ),
        migrations.AddField(
            model_name='sppd',
            name='departure_place',
            field=models.CharField(default='KANTOR Jl. Islamic Center No. 01 Citra Raya', max_length=255, verbose_name='Tempat Berangkat'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='duration_days',
            field=models.IntegerField(default=1, verbose_name='Lamanya Perjalanan Dinas (Hari)'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Tambahan'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='purpose',
            field=models.TextField(default='-', verbose_name='Maksud Perjalanan Dinas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sppd',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='sppd_reports/%Y/%m/', verbose_name='File Laporan / Bukti Foto Kegiatan'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='report_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ringkasan Hasil Perjalanan Dinas'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='signed_by_ketua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_sppd_as_ketua', to='users.employee', verbose_name='Ketua BAZNAS (Penandatangan)'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft / Pengajuan'), ('disetujui', 'Disetujui / Diterbitkan'), ('berlangsung', 'Sedang Perjalanan Dinas'), ('selesai', 'Selesai & Laporan Terunggah'), ('dibatalkan', 'Dibatalkan')], default='disetujui', max_length=20, verbose_name='Status SPPD'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='task_letter_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Surat Tugas (Contoh: 0182/ST-BAZNAS-TGN/VII/2026)'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='sppd_assignments', to='users.employee', verbose_name='Amil / Pegawai yang Diperintah'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='budget_source',
            field=models.CharField(default='BAZNAS Kabupaten Tangerang', max_length=255, verbose_name='Pembebanan Anggaran'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Tempat Tujuan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='disposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppd_list', to='dispositions.disposition', verbose_name='Disposisi Acuan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='sppd_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomor SPPD (Contoh: 0826/SPPD-BAZNAS-TGN/VII/2026)'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='transportation',
            field=models.CharField(default='Mobil', max_length=100, verbose_name='Alat Angkutan yang Digunakan'),
        ),
    ]
