# Generated by Django 4.2.30 on 2026-07-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0002_alter_surattugas_options_remove_surattugas_status_and_more'),
        ('dispositions', '0012_alter_disposition_inst_selesaikan_and_more'),
        ('sppd_service', '0007_alter_sppd_options_sppd_departure_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sppd',
            name='task_letter_number',
        ),
        migrations.AddField(
            model_name='sppd',
            name='surat_tugas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sppd_records', to='surat_tugas.surattugas', verbose_name='Dasar Surat Tugas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sppd',
            name='disposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppd_list', to='dispositions.disposition', verbose_name='Disposisi Acuan (Opsional)'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='sppd_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomor SPPD'),
        ),
    ]
