# Generated by Django 4.2.30 on 2026-08-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0002_alter_surattugas_options_remove_surattugas_status_and_more'),
        ('sppd_service', '0008_remove_sppd_task_letter_number_sppd_surat_tugas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppd',
            name='surat_tugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppd_records', to='surat_tugas.surattugas', verbose_name='Dasar Surat Tugas'),
        ),
    ]
