# Generated by Django 4.2.30 on 2026-08-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd_service', '0009_alter_sppd_surat_tugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='sppd_type',
            field=models.CharField(choices=[('survei', 'Survei / Verifikasi Lapangan'), ('penyaluran', 'Penyaluran Bantuan / Pentasyarufan'), ('umum', 'Umum / Perjalanan Dinas Lainnya')], default='umum', max_length=20, verbose_name='Jenis/Tujuan SPPD'),
        ),
        migrations.AddField(
            model_name='sppd',
            name='tahap',
            field=models.PositiveIntegerField(default=1, help_text='SPPD pertama=1, kedua=2, dst. Otomatis dihitung saat dibuat.', verbose_name='Tahap SPPD ke-'),
        ),
    ]
