# Generated by Django 4.2.30 on 2026-08-09 12:29

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd_service', '0010_sppd_type_tahap_multistage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='sppd_reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='File Laporan / Bukti Foto Kegiatan'),
        ),
        migrations.AlterField(
            model_name='sppd',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft / Pengajuan'), ('disetujui', 'Disetujui / Diterbitkan'), ('berlangsung', 'Sedang Perjalanan Dinas'), ('selesai', 'Selesai & Laporan Terunggah'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='disetujui', max_length=20, verbose_name='Status SPPD'),
        ),
    ]
