# Generated by Django 4.2.30 on 2026-08-12 00:09

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sppd_service', '0011_alter_sppd_created_at_alter_sppd_report_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPPDAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sppd_reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='File Lampiran Tambahan')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan / Nama File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sppd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_attachments', to='sppd_service.sppd')),
            ],
        ),
    ]
