# Generated by Django 4.2.30 on 2026-08-09 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomor Risalah / Agenda')),
                ('title', models.CharField(max_length=255, verbose_name='Judul / Perihal Rapat')),
                ('meeting_type', models.CharField(choices=[('pimpinan', 'Rapat Pimpinan (Rapim)'), ('pleno', 'Rapat Pleno Bidang'), ('evaluasi', 'Rapat Evaluasi & Koordinasi'), ('khusus', 'Rapat Internal / Khusus')], default='pimpinan', max_length=30, verbose_name='Jenis Rapat')),
                ('scheduled_at', models.DateTimeField(verbose_name='Waktu & Tanggal Pelaksanaan')),
                ('location', models.CharField(default='Ruang Rapat Utama BAZNAS', max_length=255, verbose_name='Tempat / Ruang Rapat')),
                ('agenda_topics', models.TextField(verbose_name='Agenda & Topik Pembahasan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='meetings/attachments/%Y/%m/', verbose_name='Berkas Lampiran / Undangan')),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('berlangsung', 'Sedang Berlangsung'), ('selesai', 'Selesai (Notulensi Terbit)'), ('dibatalkan', 'Dibatalkan')], default='terjadwal', max_length=20, verbose_name='Status Rapat')),
                ('notulensi_summary', models.TextField(blank=True, null=True, verbose_name='Ringkasan Pembahasan & Risalah')),
                ('notulensi_decision', models.TextField(blank=True, null=True, verbose_name='Kesimpulan & Keputusan Rapat')),
                ('notulensi_action_items', models.TextField(blank=True, null=True, verbose_name='Rencana Tindak Lanjut (Action Plan)')),
                ('notulensi_file', models.FileField(blank=True, null=True, upload_to='meetings/notulensi/%Y/%m/', verbose_name='Dokumen Bukti / Foto Notulensi')),
                ('notulensi_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Notulensi Disimpan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_internal_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_internal_meetings', to='users.employee', verbose_name='Pimpinan Rapat')),
                ('notulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_notulensi', to='users.employee', verbose_name='Notulis Rapat')),
                ('participants', models.ManyToManyField(blank=True, related_name='attended_internal_meetings', to='users.employee', verbose_name='Peserta Rapat (Pegawai / Amil)')),
            ],
            options={
                'verbose_name': 'Rapat Internal',
                'verbose_name_plural': 'Daftar Rapat Internal',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
