# Generated by Django 4.2.30 on 2026-08-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_profile_picture'),
        ('internal_meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmeeting',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='led_internal_meetings_m2m', to='users.employee', verbose_name='Pimpinan Rapat (Multi)'),
        ),
        migrations.AlterField(
            model_name='internalmeeting',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_internal_meetings', to='users.employee', verbose_name='Pimpinan Rapat Utama'),
        ),
    ]
