# Generated by Django 4.2.30 on 2026-08-09 12:29

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_meetings', '0002_internalmeeting_leaders_alter_internalmeeting_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmeeting',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='meetings/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='Berkas Lampiran / Undangan'),
        ),
        migrations.AlterField(
            model_name='internalmeeting',
            name='notulensi_file',
            field=models.FileField(blank=True, null=True, upload_to='meetings/notulensi/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='Dokumen Bukti / Foto Notulensi'),
        ),
        migrations.AlterField(
            model_name='internalmeeting',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, verbose_name='Waktu & Tanggal Pelaksanaan'),
        ),
        migrations.AlterField(
            model_name='internalmeeting',
            name='status',
            field=models.CharField(choices=[('terjadwal', 'Terjadwal'), ('berlangsung', 'Sedang Berlangsung'), ('selesai', 'Selesai (Notulensi Terbit)'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='terjadwal', max_length=20, verbose_name='Status Rapat'),
        ),
    ]
