# Generated by Django 4.2.30 on 2026-08-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_employee_photo'),
        ('internal_meetings', '0003_alter_internalmeeting_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tindak Lanjut / Action Item')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Target Selesai / Deadline')),
                ('is_tracked', models.BooleanField(default=True, verbose_name='Jadikan Action Plan Terlacak')),
                ('status', models.CharField(choices=[('pending', 'Belum Dimulai'), ('in_progress', 'Sedang Diproses'), ('completed', 'Selesai / Terealisasi'), ('overdue', 'Terlambat')], db_index=True, default='pending', max_length=20, verbose_name='Status Realisasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Realisasi / Progress')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_action_items', to=settings.AUTH_USER_MODEL, verbose_name='Diselesaikan Oleh')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='internal_meetings.internalmeeting', verbose_name='Rapat Internal')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to='users.employee', verbose_name='Penanggung Jawab (PIC)')),
            ],
            options={
                'verbose_name': 'Tindak Lanjut Rapat',
                'verbose_name_plural': 'Daftar Tindak Lanjut Rapat',
                'ordering': ['id'],
            },
        ),
    ]
