# Generated by Django 4.2.30 on 2026-08-15 15:48

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_meetings', '0004_meetingactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingactionitem',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='meetings/action_plan_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='Dokumen Bukti / File Hasil Realisasi'),
        ),
    ]
