# Generated by Django 4.2.30 on 2026-08-16 23:08

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal_meetings', '0005_meetingactionitem_proof_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNotulensiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meetings/notulensi_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='Dokumen Bukti / Foto Notulensi')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Berkas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notulensi_attachments', to='internal_meetings.internalmeeting', verbose_name='Rapat Internal')),
            ],
            options={
                'verbose_name': 'Lampiran Notulensi Rapat',
                'verbose_name_plural': 'Daftar Lampiran Notulensi Rapat',
                'ordering': ['id'],
            },
        ),
    ]
