# Generated by Django 4.2.30 on 2026-08-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_meetings', '0006_meetingnotulensiattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmeeting',
            name='guest_names',
            field=models.TextField(blank=True, null=True, verbose_name='Daftar Tamu / Perwakilan Tamu (Ditulis Manual)'),
        ),
        migrations.AlterField(
            model_name='internalmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('pimpinan', 'Rapat Pimpinan (Rapim)'), ('pleno', 'Rapat Pleno Bidang'), ('evaluasi', 'Rapat Evaluasi & Koordinasi'), ('khusus', 'Rapat Internal / Khusus'), ('audiensi', 'Audiensi / Penerimaan Tamu / Kerja Sama')], default='pimpinan', max_length=30, verbose_name='Jenis Rapat'),
        ),
    ]
