# Generated by Django 4.2.30 on 2026-06-06 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposition',
            name='receiver',
        ),
        migrations.AddField(
            model_name='disposition',
            name='forwarded_to',
            field=models.ManyToManyField(related_name='received_dispositions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_koordinasikan',
            field=models.BooleanField(default=False, verbose_name='Koordinasikan'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_laporkan_hasilnya',
            field=models.BooleanField(default=False, verbose_name='Laporkan hasilnya'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_salinan_fc',
            field=models.BooleanField(default=False, verbose_name='Salinan / FC'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_saran_pendapat',
            field=models.BooleanField(default=False, verbose_name='Saran/Pendapat'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_selesaikan',
            field=models.BooleanField(default=False, verbose_name='Selesaikan'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_untuk_diketahui',
            field=models.BooleanField(default=False, verbose_name='Untuk diketahui'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='inst_untuk_diproses',
            field=models.BooleanField(default=False, verbose_name='Untuk diproses'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='priority',
            field=models.CharField(choices=[('segera', 'Segera'), ('penting', 'Penting'), ('biasa', 'Biasa')], default='biasa', max_length=20),
        ),
        migrations.AddField(
            model_name='disposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='note',
            field=models.TextField(blank=True, verbose_name='Catatan Pimpinan'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('terisi', 'Menunggu Verifikasi'), ('terverifikasi', 'Terverifikasi'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
