# Generated by Django 4.2.30 on 2026-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0003_remove_disposition_receiver_disposition_forwarded_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposition',
            name='inst_salinan_fc',
        ),
        migrations.RemoveField(
            model_name='disposition',
            name='inst_saran_pendapat',
        ),
        migrations.RemoveField(
            model_name='disposition',
            name='inst_untuk_diproses',
        ),
        migrations.AlterField(
            model_name='disposition',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('terisi', 'Menunggu Verifikasi'), ('terverifikasi', 'Terverifikasi'), ('proses', 'Proses (SPPD)'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
