# Generated by Django 4.2.30 on 2026-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0004_remove_disposition_inst_salinan_fc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='implementation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pelaksanaan'),
        ),
    ]
