# Generated by Django 4.2.30 on 2026-06-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0005_disposition_implementation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='disposition_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
