# Generated by Django 4.2.30 on 2026-07-19 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0007_change_forwarded_to_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_dispositions', to='dispositions.disposition', verbose_name='Turunan Dari Disposisi'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='note',
            field=models.TextField(blank=True, verbose_name='Catatan/Instruksi Tambahan'),
        ),
    ]
