# Generated by Django 4.2.30 on 2026-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0008_disposition_parent_alter_disposition_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='checked_by_kabid',
            field=models.BooleanField(default=False, verbose_name='Telah Diperiksa/Diverifikasi Kabid 4'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='kabid_note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Khusus Kabid 4'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='requires_sppd',
            field=models.BooleanField(default=False, verbose_name='Memerlukan SPPD / Dinas Luar'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='implementation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pelaksanaan / Audiensi'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='note',
            field=models.TextField(blank=True, verbose_name='Catatan/Instruksi Tambahan Pimpinan'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru (Menunggu Disposisi)'), ('terisi', 'Menunggu Verifikasi'), ('terverifikasi', 'Terverifikasi'), ('proses', 'Proses (Bidang / SPPD)'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
