# Generated by Django 4.2.30 on 2026-07-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_options_alter_employee_options_and_more'),
        ('dispositions', '0009_disposition_checked_by_kabid_disposition_kabid_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Disposisi', 'verbose_name_plural': 'Daftar Disposisi'},
        ),
        migrations.AddField(
            model_name='disposition',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diselesaikan'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/dispositions/results/', verbose_name='Dokumen Bukti Tindak Lanjut'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='result_note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Hasil Tindak Lanjut'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='forwarded_to',
            field=models.ManyToManyField(blank=True, related_name='received_dispositions', to='users.employee'),
        ),
    ]
