# Generated by Django 4.2.30 on 2026-07-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0010_alter_disposition_options_disposition_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru (Menunggu Disposisi)'), ('terisi', 'Menunggu Verifikasi'), ('terverifikasi', 'Terverifikasi'), ('proses', 'Proses (Bidang / Tindak Lanjut)'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
