# Generated by Django 4.2.30 on 2026-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0011_alter_disposition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='inst_selesaikan',
            field=models.BooleanField(default=False, verbose_name='Selesaikan / Jawab'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='inst_untuk_diketahui',
            field=models.BooleanField(default=False, verbose_name='Untuk diketahui / Simpan'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='priority',
            field=models.CharField(choices=[('sangat_segera', 'Sangat Segera'), ('segera', 'Segera'), ('penting', 'Penting / Mendesak'), ('biasa', 'Biasa')], default='biasa', max_length=20),
        ),
    ]
