# Generated by Django 4.2.30 on 2026-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0012_alter_disposition_inst_selesaikan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='status',
            field=models.CharField(choices=[('baru', 'Menunggu Disposisi'), ('terisi', 'Disposisi Aktif'), ('terverifikasi', 'Siap Didisposisikan'), ('proses', 'Disposisi Aktif'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
