# Generated by Django 4.2.30 on 2026-08-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0014_disposition_2stage_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='disposition_stage',
            field=models.CharField(choices=[('ketua', 'Disposisi Ketua'), ('waka_iv', 'Disposisi Waka IV')], db_index=True, default='ketua', max_length=20, verbose_name='Tahap Disposisi'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='status',
            field=models.CharField(choices=[('baru', 'Menunggu Disposisi Ketua'), ('didisposisi_ketua', 'Sudah Disposisi Ketua — Menunggu Waka IV'), ('proses', 'Sedang Diproses Bidang'), ('selesai', 'Selesai')], db_index=True, default='baru', max_length=30),
        ),
    ]
