# Generated by Django 4.2.30 on 2026-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='SI-ARSIP SDM BAZNAS', max_length=255)),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='app_assets/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
