# Generated by Django 4.2.30 on 2026-06-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_department_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Superadmin'), ('pimpinan', 'Pimpinan'), ('staff', 'Staff SDM')], default='staff', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
