# Generated by Django 4.2.30 on 2026-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Superadmin'), ('pimpinan', 'Pimpinan'), ('kabid', 'Kabid'), ('staff', 'Staff Receptionis')], default='staff', max_length=20),
        ),
    ]
