# Generated by Django 4.2.30 on 2026-07-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_kabid_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='users.department', verbose_name='Induk Bidang/Bagian'),
        ),
        migrations.AddField(
            model_name='employee',
            name='acting_in_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_employees', to='users.department', verbose_name='Menjabat Sebagai Plt di Bidang'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_acting_role',
            field=models.BooleanField(default=False, verbose_name='Status Jabatan Plt Aktif'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leadership_type',
            field=models.CharField(choices=[('ketua', 'Ketua'), ('waka_1', 'Wakil Ketua I (Pengumpulan)'), ('waka_2', 'Wakil Ketua II (Pendistribusian & Pendayagunaan)'), ('waka_3', 'Wakil Ketua III (Perencanaan, Keuangan & Pelaporan)'), ('waka_4', 'Wakil Ketua IV (Administrasi, SDM & Umum)'), ('none', 'Bukan Pimpinan / Struktur Standar')], default='none', max_length=20, verbose_name='Tipe Pimpinan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.department', verbose_name='Bidang/Bagian Utama'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Nama Jabatan (e.g., Staf Pelaksana)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Superadmin'), ('pimpinan', 'Pimpinan (Ketua/Waka)'), ('kabid', 'Kepala Bidang/Bagian'), ('staff', 'Staf / Resepsionis')], default='staff', max_length=20),
        ),
    ]
