# Generated by Django 4.2.30 on 2026-07-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_parent_employee_acting_in_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Bidang / Bagian', 'verbose_name_plural': 'Bidang / Bagian'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Pegawai / Amil', 'verbose_name_plural': 'Pegawai / Amil'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Bidang / Bagian'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alamat Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nama Lengkap & Gelar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif Pegawai'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leadership_type',
            field=models.CharField(choices=[('ketua', 'Ketua BAZNAS'), ('waka_1', 'Wakil Ketua I (Pengumpulan)'), ('waka_2', 'Wakil Ketua II (Pendistribusian & Pendayagunaan)'), ('waka_3', 'Wakil Ketua III (Perencanaan, Keuangan & Pelaporan)'), ('waka_4', 'Wakil Ketua IV (Administrasi, SDM & Umum)'), ('none', 'Bukan Pimpinan / Struktur Standar')], default='none', max_length=20, verbose_name='Tipe Pimpinan BAZNAS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nip',
            field=models.CharField(max_length=50, unique=True, verbose_name='NIP / NIK'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. WhatsApp / Telepon'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Nama Jabatan (Contoh: Staf Pelaksana Administrasi, SDM dan Umum)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='users.employee', verbose_name='Profil Pegawai / Amil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_account',
            field=models.BooleanField(default=True, verbose_name='Akun Aktif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Superadmin'), ('pimpinan', 'Pimpinan (Ketua/Waka)'), ('kabid', 'Kepala Bidang/Bagian'), ('staff', 'Staf / Resepsionis')], default='staff', max_length=20, verbose_name='Peran Akun'),
        ),
    ]
