# Generated by Django 4.2.30 on 2026-07-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
