# Generated by Django 4.2.30 on 2026-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Lengkap Tempat Tinggal'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('amil_tetap', 'Amil Tetap'), ('amil_kontrak', 'Amil Kontrak'), ('honorer', 'Pegawai Honorer'), ('magang', 'Staf Magang / PKL')], default='amil_tetap', max_length=30, verbose_name='Status Kepegawaian'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pendidikan Terakhir'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nik_ktp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. NIK KTP (16 Digit)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sk_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Terbit SK'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sk_file',
            field=models.FileField(blank=True, null=True, upload_to='sk_pegawai/', verbose_name='File Berkas SK (PDF/Gambar)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sk_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor SK Pengangkatan / SK Amil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tmt_date',
            field=models.DateField(blank=True, null=True, verbose_name='TMT (Terhitung Mulai Tanggal) Bergabung'),
        ),
    ]
