# Generated by Django 4.2.30 on 2026-06-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='agendas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
