# Generated by Django 4.2.30 on 2026-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agenda_assigned_to_agenda_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='agendas/completed/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='completed_notes',
            field=models.TextField(blank=True),
        ),
    ]
