# Generated by Django 4.2.30 on 2026-06-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_agenda_completed_file_agenda_completed_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('terjadwal', 'Terjadwal'), ('diundur', 'Diundur'), ('dibatalkan', 'Dibatalkan'), ('selesai', 'Selesai')], default='terjadwal', max_length=20),
        ),
    ]
