# Generated by Django 4.2.30 on 2026-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_agenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notifikasi terakhir dikirim'),
        ),
    ]
