# Generated by Django 4.2.30 on 2026-07-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_remove_archive_sender_receiver_archive_received_date_and_more'),
        ('agendas', '0005_add_notification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempat / Lokasi Kegiatan'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to='archives.archive'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='agendas/%Y/%m/%d/', verbose_name='File Lampiran'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='agendas/completed/%Y/%m/%d/', verbose_name='Dokumentasi / Hasil Kegiatan'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='completed_notes',
            field=models.TextField(blank=True, verbose_name='Catatan Penyelesaian / Notulensi'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi / Acara'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='Waktu Pelaksanaan'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nama Kegiatan / Agenda'),
        ),
    ]
