# Generated by Django 4.2.30 on 2026-07-21 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_alter_category_options_archive_kabid_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_alter_department_options_alter_employee_options_and_more'),
        ('agendas', '0006_agenda_location_alter_agenda_archive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Agenda Kerja', 'verbose_name_plural': 'Agenda Kerja BAZNAS'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_agendas', to='users.employee', verbose_name='Ditugaskan ke Pegawai'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Waktu Diperbarui'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to='archives.archive', verbose_name='Arsip / Dokumen Terkait'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_agendas', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan ke User'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='agendas/%Y/%m/%d/', verbose_name='File Lampiran / Undangan'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agendas', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Status Selesai'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notifikasi Terakhir Dikirim'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('terjadwal', 'Terjadwal'), ('diundur', 'Diundur'), ('dibatalkan', 'Dibatalkan'), ('selesai', 'Selesai')], default='terjadwal', max_length=20, verbose_name='Status Agenda'),
        ),
    ]
