# Generated by Django 4.2.30 on 2026-08-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0008_add_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='external_event_id',
            field=models.CharField(blank=True, help_text='ID on external calendar provider if synced', max_length=255, null=True),
        ),
    ]
