# Generated by Django 4.2.30 on 2026-08-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0009_alter_calendarevent_external_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='agendas/attachments/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='agendas.agenda')),
            ],
        ),
    ]
