# Generated by Django 4.2.30 on 2026-08-09 12:29

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0010_agendaattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='agendas/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='File Lampiran / Undangan'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='completed_file',
            field=models.FileField(blank=True, null=True, upload_to='agendas/completed/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size], verbose_name='Dokumentasi / Hasil Kegiatan'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, verbose_name='Waktu Pelaksanaan'),
        ),
        migrations.AlterField(
            model_name='agendaattachment',
            name='file',
            field=models.FileField(upload_to='agendas/attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Format file tidak didukung. Format yang diizinkan: PDF, DOC, DOCX, JPG, JPEG, PNG.'), core.validators.validate_file_size]),
        ),
    ]
