# Generated by Django 4.2.30 on 2026-07-21 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositions', '0012_alter_disposition_inst_selesaikan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(blank=True, help_text='Kosongkan jika masih berupa draft', max_length=100, null=True, unique=True)),
                ('tentang', models.TextField(help_text='Perihal atau tujuan penugasan')),
                ('hari_kegiatan', models.CharField(help_text='Contoh: Senin s.d. Rabu', max_length=50)),
                ('tanggal_mulai', models.DateField(help_text='Tanggal pelaksanaan kegiatan')),
                ('lokasi_tujuan', models.CharField(help_text='Tempat/lokasi pelaksanaan tugas', max_length=255)),
                ('pejabat_penandatangan', models.CharField(default='H. A. MADANI, S.Ag', max_length=150)),
                ('jabatan_penandatangan', models.CharField(default='Wakil Ketua III', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Selesai')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tugas_created', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tugas_list', to='dispositions.disposition')),
                ('pegawai_ditugaskan', models.ManyToManyField(related_name='penugasan_surat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surat Tugas',
                'verbose_name_plural': 'Surat Tugas',
                'ordering': ['-created_at'],
            },
        ),
    ]
