# Generated by Django 4.2.30 on 2026-07-23 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositions', '0012_alter_disposition_inst_selesaikan_and_more'),
        ('users', '0010_alter_user_options'),
        ('surat_tugas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surattugas',
            options={},
        ),
        migrations.RemoveField(
            model_name='surattugas',
            name='status',
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tugas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='disposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tugas', to='dispositions.disposition'),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='hari_kegiatan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='jabatan_penandatangan',
            field=models.CharField(default='Ketua BAZNAS', max_length=150),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='lokasi_tujuan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='nomor_surat',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='pegawai_ditugaskan',
            field=models.ManyToManyField(related_name='surat_tugas_list', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='pejabat_penandatangan',
            field=models.CharField(default='Drs. Achmad Nawawi, M.Si', max_length=150),
        ),
        migrations.AlterField(
            model_name='surattugas',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
