# Generated by Django 4.2.30 on 2026-08-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0002_alter_surattugas_options_remove_surattugas_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surattugas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
