# Generated by Django 4.2.30 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_file_alter_reportattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nominal Bantuan Disalurkan (Rp)'),
        ),
        migrations.AddField(
            model_name='report',
            name='disbursement_type',
            field=models.CharField(choices=[('transfer', 'Transfer Bank'), ('cash', 'Uang Tunai'), ('natura', 'Barang Natura / Sembako')], default='transfer', max_length=50, verbose_name='Bentuk Penyaluran'),
        ),
    ]
