# Generated by Django 4.2.30 on 2026-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
