# Generated by Django 4.2.30 on 2026-07-21 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_alter_department_options_alter_employee_options_and_more'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notifikasi', 'verbose_name_plural': 'Log Notifikasi'},
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('disposition', 'Disposisi'), ('sppd', 'SPPD & Surat Tugas'), ('agenda', 'Agenda Kerja'), ('archive', 'Arsip & Dokumen'), ('general', 'Umum')], default='general', max_length=30, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.employee', verbose_name='Pegawai/Amil Penerima'),
        ),
        migrations.AddField(
            model_name='notification',
            name='error_log',
            field=models.TextField(blank=True, null=True, verbose_name='Log Kendala/Error'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Tautan'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Terkirim'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Judul Notifikasi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Pesan Notifikasi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('system', 'System / Web Dashboard')], default='system', max_length=20, verbose_name='Tipe Notifikasi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Belum Dibaca'), ('read', 'Sudah Dibaca'), ('pending', 'Menunggu Pengiriman'), ('sent', 'Terkirim'), ('failed', 'Gagal Terkirim')], default='unread', max_length=20, verbose_name='Status Pengiriman/Baca'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User Penerima'),
        ),
    ]
