# Generated by Django 4.2.30 on 2026-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WANotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('disposition', 'Disposisi Pimpinan (Stage 1 & 2)'), ('bantuan_survei', 'Penugasan Survei Lapangan Bantuan (Bidang II)'), ('bantuan_penyaluran', 'LHP Penyaluran Direct (Bidang II)'), ('sppd', 'SPPD & Perjalanan Dinas'), ('internal_meeting', 'Risalah & Notulensi Rapat Internal'), ('archive', 'Notifikasi Arsip & Dokumen Baru')], max_length=50, unique=True, verbose_name='Kategori Kejadian Notifikasi')),
                ('dispatch_mode', models.CharField(choices=[('auto', '🤖 Otomatis (Auto-Dispatch Queue)'), ('manual', '💬 Manual (1-Click WA Direct Link/Trigger)'), ('disabled', '🚫 Nonaktifkan Notifikasi WA')], default='auto', max_length=20, verbose_name='Mode Pengiriman')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan Notifikasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Mode Notifikasi WA',
                'verbose_name_plural': 'Pengaturan Mode Notifikasi WA',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='dispatch_mode',
            field=models.CharField(choices=[('auto', 'Otomatis'), ('manual', 'Manual')], default='auto', max_length=20, verbose_name='Mode Pengiriman WA'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomor WA Penerima'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Jumlah Percobaan Kirim Ulang'),
        ),
        migrations.AddField(
            model_name='notification',
            name='wa_direct_link',
            field=models.TextField(blank=True, null=True, verbose_name='Direct Link WA Web / App'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('disposition', 'Disposisi'), ('bantuan_survei', 'Survei Bantuan'), ('bantuan_penyaluran', 'Penyaluran Bantuan'), ('sppd', 'SPPD & Surat Tugas'), ('internal_meeting', 'Rapat Internal'), ('agenda', 'Agenda Kerja'), ('archive', 'Arsip & Dokumen'), ('general', 'Umum')], default='general', max_length=30, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Belum Dibaca'), ('read', 'Sudah Dibaca'), ('pending', 'Menunggu Pengiriman'), ('sent', 'Terkirim'), ('failed', 'Gagal Terkirim'), ('draft_manual', 'Siap Kirim Manual')], default='unread', max_length=20, verbose_name='Status Pengiriman/Baca'),
        ),
    ]
