# Generated by Django 4.2.30 on 2026-08-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('disposition', 'Disposisi'), ('bantuan_survei', 'Survei Bantuan'), ('bantuan_penyaluran', 'Penyaluran Bantuan'), ('sppd', 'SPPD & Surat Tugas'), ('internal_meeting', 'Rapat Internal'), ('agenda', 'Agenda Kerja'), ('archive', 'Arsip & Dokumen'), ('general', 'Umum')], db_index=True, default='general', max_length=30, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Belum Dibaca'), ('read', 'Sudah Dibaca'), ('pending', 'Menunggu Pengiriman'), ('sent', 'Terkirim'), ('failed', 'Gagal Terkirim'), ('draft_manual', 'Siap Kirim Manual')], db_index=True, default='unread', max_length=20, verbose_name='Status Pengiriman/Baca'),
        ),
        migrations.AlterField(
            model_name='wanotificationsetting',
            name='category',
            field=models.CharField(choices=[('disposition', 'Disposisi Pimpinan (Stage 1 & 2)'), ('bantuan_survei', 'Penugasan Survei Lapangan Bantuan (Bidang II)'), ('bantuan_penyaluran', 'LHP Penyaluran Direct (Bidang II)'), ('sppd', 'SPPD & Perjalanan Dinas'), ('internal_meeting', 'Risalah & Notulensi Rapat Internal'), ('agenda', 'Agenda Kerja & Pengingat'), ('archive', 'Notifikasi Arsip & Dokumen Baru'), ('general', 'Umum / System Default')], max_length=50, unique=True, verbose_name='Kategori Kejadian Notifikasi'),
        ),
    ]
